name: Kararli Surumu Yayinla

on:
  workflow_run:
    workflows: [ "Python CI Otomasyonu" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  yayinla:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Kararli Dala (Stable) Gonder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b stable || git checkout stable
          git merge main
          git push origin stable --force
